const locations = [
    'Paris, France', 
    'Tokyo, Japan',
    'New York, USA',
    'London, UK',
    'Madrid, Spain',
    'Berlin, Germany',
    'Rome, Italy',
    'Sydney, Australia',
    'Beijing, China',
    'Moscow, Russia',
    'Cairo, Egypt',
    'Rio de Janeiro, Brazil',
    'Buenos Aires, Argentina',
    'Lima, Peru',
    'Mexico City, Mexico',
    'Toronto, Canada',
    'Cape Town, South Africa',
    'Mumbai, India',
    'Seoul, South Korea',
    'Jakarta, Indonesia',
    'Hong Kong, China',
    'Hanoi, Vietnam',
    'Bangkok, Thailand',
    'Taipei, Taiwan',
    'Manila, Philippines',
    'Kuala Lumpur, Malaysia',
    'Singapore, Singapore',
    'Wellington, New Zealand',
]

export default locations;